// Mock video data for StreamNova
export const VIDEOS = [
  {
    id: 'v1',
    title: 'The Ocean\'s Secrets: A Deep Dive Into Marine Life',
    channel: 'NatureVision',
    channelAvatar: 'NV',
    views: '4.2M',
    duration: '18:24',
    timestamp: '3 days ago',
    thumbnail: 'https://loremflickr.com/640/360/ocean?lock=1',
    category: 'Nature',
    tier: 'free',
    description: 'Explore the breathtaking world beneath the ocean surface. This documentary takes you on a journey through coral reefs, deep sea trenches, and mysterious underwater caves.',
    likes: 142000,
    dislikes: 1200,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v2',
    title: 'Advanced React Patterns: Build Production-Ready Apps',
    channel: 'DevMastery',
    channelAvatar: 'DM',
    views: '892K',
    duration: '42:11',
    timestamp: '1 week ago',
    thumbnail: 'https://loremflickr.com/640/360/code?lock=2',
    category: 'Technology',
    tier: 'bronze',
    description: 'Master advanced React patterns including compound components, render props, custom hooks, and performance optimization techniques.',
    likes: 38000,
    dislikes: 320,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v3',
    title: 'Tokyo After Dark: Neon Streets & Hidden Cafés',
    channel: 'WorldExplorer',
    channelAvatar: 'WE',
    views: '2.1M',
    duration: '24:50',
    timestamp: '5 days ago',
    thumbnail: 'https://loremflickr.com/640/360/tokyo?lock=3',
    category: 'Travel',
    tier: 'free',
    description: 'Journey through Tokyo\'s mesmerizing nightlife, from glowing izakayas to silent temples that stand between skyscrapers.',
    likes: 95000,
    dislikes: 800,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v4',
    title: 'Cooking Michelin: Restaurant-Level Techniques at Home',
    channel: 'ChefElite',
    channelAvatar: 'CE',
    views: '3.7M',
    duration: '31:05',
    timestamp: '2 days ago',
    thumbnail: 'https://loremflickr.com/640/360/cooking?lock=4',
    category: 'Food',
    tier: 'silver',
    description: 'Learn the secret techniques used by Michelin-star chefs. From perfect sauces to plating like a professional.',
    likes: 210000,
    dislikes: 1800,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v5',
    title: 'Space Telescope\'s Most Stunning Images of 2025',
    channel: 'CosmosTV',
    channelAvatar: 'CT',
    views: '8.4M',
    duration: '15:37',
    timestamp: '1 day ago',
    thumbnail: 'https://loremflickr.com/640/360/space?lock=5',
    category: 'Science',
    tier: 'gold',
    description: 'The James Webb Telescope has revealed breathtaking images of distant galaxies, nebulae, and star-forming regions.',
    likes: 680000,
    dislikes: 3200,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v6',
    title: 'Electric Guitar Mastery: From Beginner to Shredder',
    channel: 'MusicLab',
    channelAvatar: 'ML',
    views: '1.2M',
    duration: '56:22',
    timestamp: '2 weeks ago',
    thumbnail: 'https://loremflickr.com/640/360/guitar?lock=6',
    category: 'Music',
    tier: 'bronze',
    description: 'Complete electric guitar course covering basics, scales, chord theory, and advanced techniques for all skill levels.',
    likes: 67000,
    dislikes: 590,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v7',
    title: 'Cyberpunk City Design: Blender 3D Architecture',
    channel: 'ArtForge',
    channelAvatar: 'AF',
    views: '540K',
    duration: '38:14',
    timestamp: '4 days ago',
    thumbnail: 'https://loremflickr.com/640/360/cyberpunk?lock=7',
    category: 'Art',
    tier: 'free',
    description: 'Create a stunning futuristic cyberpunk cityscape in Blender 3D. Full workflow from concept to final render.',
    likes: 29000,
    dislikes: 280,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v8',
    title: 'The Psychology of Success: Habits of Top Performers',
    channel: 'MindGrowth',
    channelAvatar: 'MG',
    views: '5.6M',
    duration: '22:48',
    timestamp: '6 days ago',
    thumbnail: 'https://loremflickr.com/640/360/books?lock=8',
    category: 'Education',
    tier: 'free',
    description: 'Discover the mental models, habits, and mindsets shared by the world\'s most successful people across different fields.',
    likes: 312000,
    dislikes: 2100,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v9',
    title: 'Formula 1 2025: The Most Dramatic Overtakes',
    channel: 'SpeedWorld',
    channelAvatar: 'SW',
    views: '11.2M',
    duration: '19:30',
    timestamp: '12 hours ago',
    thumbnail: 'https://loremflickr.com/640/360/racing?lock=9',
    category: 'Sports',
    tier: 'gold',
    description: 'Relive the most heart-stopping overtakes of the 2025 Formula 1 season with onboard footage and commentary.',
    likes: 890000,
    dislikes: 4500,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v10',
    title: 'Minimalist Interior Design: Less is More',
    channel: 'DesignNest',
    channelAvatar: 'DN',
    views: '1.8M',
    duration: '27:15',
    timestamp: '3 weeks ago',
    thumbnail: 'https://loremflickr.com/640/360/interior?lock=10',
    category: 'Lifestyle',
    tier: 'free',
    description: 'Transform your living space with minimalist design principles. Expert tips on furniture, lighting, and decluttering.',
    likes: 98000,
    dislikes: 720,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v11',
    title: 'AI Tools That Changed My Workflow Forever',
    channel: 'TechPro',
    channelAvatar: 'TP',
    views: '2.9M',
    duration: '14:52',
    timestamp: '2 days ago',
    thumbnail: 'https://loremflickr.com/640/360/technology?lock=11',
    category: 'Technology',
    tier: 'free',
    description: 'My top 10 AI tools that have revolutionized how I work, create, and collaborate. Honest reviews and demonstrations.',
    likes: 180000,
    dislikes: 1500,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
  {
    id: 'v12',
    title: 'Yoga Flow: 60-Minute Morning Energizer',
    channel: 'ZenMoves',
    channelAvatar: 'ZM',
    views: '4.4M',
    duration: '60:00',
    timestamp: '5 days ago',
    thumbnail: 'https://loremflickr.com/640/360/yoga?lock=12',
    category: 'Fitness',
    tier: 'silver',
    description: 'A rejuvenating 60-minute yoga flow designed to energize your body and calm your mind. Suitable for all levels.',
    likes: 215000,
    dislikes: 1100,
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
  },
];

export const CATEGORIES = ['All', 'Nature', 'Technology', 'Travel', 'Food', 'Science', 'Music', 'Art', 'Education', 'Sports', 'Lifestyle', 'Fitness'];

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    priceLabel: '₹0',
    priceSub: 'Forever Free',
    icon: '',
    watchLimit: 5,
    watchLimitLabel: '5 minutes/video',
    downloads: 1,
    downloadsLabel: '1 download/day',
    features: [
      { text: 'Watch up to 5 min/video', included: true },
      { text: '1 download per day', included: true },
      { text: 'HD quality streaming', included: true },
      { text: 'Basic comment features', included: true },
      { text: 'AI comment translation', included: false },
      { text: 'VoIP & Video calls', included: false },
      { text: 'Unlimited downloads', included: false },
      { text: 'Priority support', included: false },
    ],
    razorpayPlanId: null,
    color: 'free',
  },
  {
    id: 'bronze',
    name: 'Bronze',
    price: 99,
    priceLabel: '₹99',
    priceSub: 'per month',
    icon: '',
    watchLimit: 7,
    watchLimitLabel: '7 minutes/video',
    downloads: 3,
    downloadsLabel: '3 downloads/day',
    features: [
      { text: 'Watch up to 7 min/video', included: true },
      { text: '3 downloads per day', included: true },
      { text: 'Full HD streaming', included: true },
      { text: 'AI comment translation', included: true },
      { text: 'VoIP & Video calls', included: false },
      { text: 'Screen sharing', included: false },
      { text: 'Unlimited downloads', included: false },
      { text: 'Priority support', included: false },
    ],
    razorpayPlanId: 'plan_bronze_001',
    color: 'bronze',
  },
  {
    id: 'silver',
    name: 'Silver',
    price: 199,
    priceLabel: '₹199',
    priceSub: 'per month',
    icon: '',
    watchLimit: 10,
    watchLimitLabel: '10 minutes/video',
    downloads: -1,
    downloadsLabel: 'Unlimited downloads',
    popular: true,
    features: [
      { text: 'Watch up to 10 min/video', included: true },
      { text: 'Unlimited downloads', included: true },
      { text: '4K quality streaming', included: true },
      { text: 'AI comment translation', included: true },
      { text: 'VoIP & Video calls', included: true },
      { text: 'Screen sharing', included: true },
      { text: 'Session recording', included: false },
      { text: 'Priority support', included: true },
    ],
    razorpayPlanId: 'plan_silver_001',
    color: 'silver',
  },
  {
    id: 'gold',
    name: 'Gold',
    price: 399,
    priceLabel: '₹399',
    priceSub: 'per month',
    icon: '',
    watchLimit: -1,
    watchLimitLabel: 'Unlimited streaming',
    downloads: -1,
    downloadsLabel: 'Unlimited downloads',
    popularGold: true,
    features: [
      { text: 'Unlimited streaming', included: true },
      { text: 'Unlimited downloads', included: true },
      { text: '4K + HDR streaming', included: true },
      { text: 'AI comment translation', included: true },
      { text: 'VoIP & Video calls', included: true },
      { text: 'Screen sharing', included: true },
      { text: 'Session recording', included: true },
      { text: 'Dedicated priority support', included: true },
    ],
    razorpayPlanId: 'plan_gold_001',
    color: 'gold',
  },
];

export const SOUTH_INDIAN_STATES = ['Tamil Nadu', 'Karnataka', 'Kerala', 'Andhra Pradesh', 'Telangana'];

export const MOCK_COMMENTS = [
  {
    id: 'c1',
    userId: 'u1',
    userName: 'Arjun Sharma',
    city: 'Mumbai',
    text: 'This video is absolutely incredible! The production quality is outstanding.',
    originalText: null,
    originalLang: 'en',
    timestamp: '2 hours ago',
    likes: 142,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
  },
  {
    id: 'c2',
    userId: 'u2',
    userName: 'Priya Nair',
    city: 'Chennai',
    text: 'இந்த வீடியோ மிகவும் அருமையாக இருக்கிறது! மிகவும் நன்றி.',
    originalText: 'இந்த வீடியோ மிகவும் அருமையாக இருக்கிறது! மிகவும் நன்றி.',
    originalLang: 'ta',
    timestamp: '1 hour ago',
    likes: 89,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
  },
  {
    id: 'c3',
    userId: 'u3',
    userName: 'Carlos Rodriguez',
    city: 'Madrid',
    text: '¡Fantástico contenido! Aprendí mucho con este video.',
    originalText: '¡Fantástico contenido! Aprendí mucho con este video.',
    originalLang: 'es',
    timestamp: '45 min ago',
    likes: 34,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
  },
  {
    id: 'c4',
    userId: 'u4',
    userName: 'Yuki Tanaka',
    city: 'Tokyo',
    text: 'とても素晴らしい動画です！もっと見たいです。',
    originalText: 'とても素晴らしい動画です！もっと見たいです。',
    originalLang: 'ja',
    timestamp: '30 min ago',
    likes: 56,
    dislikes: 0,
    likedBy: [],
    dislikedBy: [],
  },
];

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'ja', name: 'Japanese' },
  { code: 'zh', name: 'Chinese' },
  { code: 'ar', name: 'Arabic' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
];
